### PR TITLE
Upgrade this to Go 1.7 manually

### PR DESCRIPTION
**Pull request by Xe**
Slipstreams golang:1.7 source dockerfile into this dockerfile.

### CODE REVIEW

**Comment by voutasaurus** [comment]
LGTM :)

**Comment by joshi4** [comment]
@xe: the upstream seems to have been updated. perhaps all we need to do is rebuild the image.

**Comment by joshi4** [comment]
I'm not a fan of us having to maintain the upstream ourselves.

**Comment by voutasaurus** [comment]
@joshi4 The upstream Dockerfile was updated but the image wasn't pushed. This was a temporary fix to deploy the golangjava package for wercker. 

We can fix this when the next version of Go comes around

**Pull request merged**
